
default: \
it


alloc.o: \
default.o.build \
compile \
alloc.c \
alloc.h \
error.h
	sh makefile.build default.o.build alloc.o alloc

alloc_re.o: \
default.o.build \
compile \
alloc_re.c \
alloc.h \
byte.h
	sh makefile.build default.o.build alloc_re.o alloc_re

auto-str: \
default.build \
auto-str=x \
load \
auto-str.o \
unix.a
	sh makefile.build default.build auto-str auto-str

auto-str.o: \
default.o.build \
compile \
auto-str.c \
buffer.h \
exit.h
	sh makefile.build default.o.build auto-str.o auto-str

auto_home.c: \
auto_home.c.build \
auto-str \
home
	sh makefile.build auto_home.c.build auto_home.c 

auto_home.o: \
default.o.build \
compile \
auto_home.c
	sh makefile.build default.o.build auto_home.o auto_home

buffer.o: \
default.o.build \
compile \
buffer.c \
buffer.h
	sh makefile.build default.o.build buffer.o buffer

buffer_0.o: \
default.o.build \
compile \
buffer_0.c \
buffer.h
	sh makefile.build default.o.build buffer_0.o buffer_0

buffer_1.o: \
default.o.build \
compile \
buffer_1.c \
buffer.h
	sh makefile.build default.o.build buffer_1.o buffer_1

buffer_2.o: \
default.o.build \
compile \
buffer_2.c \
buffer.h
	sh makefile.build default.o.build buffer_2.o buffer_2

buffer_copy.o: \
default.o.build \
compile \
buffer_copy.c \
buffer.h
	sh makefile.build default.o.build buffer_copy.o buffer_copy

buffer_get.o: \
default.o.build \
compile \
buffer_get.c \
buffer.h \
byte.h \
error.h
	sh makefile.build default.o.build buffer_get.o buffer_get

buffer_put.o: \
default.o.build \
compile \
buffer_put.c \
buffer.h \
str.h \
byte.h \
error.h
	sh makefile.build default.o.build buffer_put.o buffer_put

buffer_read.o: \
default.o.build \
compile \
buffer_read.c \
buffer.h
	sh makefile.build default.o.build buffer_read.o buffer_read

buffer_write.o: \
default.o.build \
compile \
buffer_write.c \
buffer.h
	sh makefile.build default.o.build buffer_write.o buffer_write

byte_chr.o: \
default.o.build \
compile \
byte_chr.c \
byte.h
	sh makefile.build default.o.build byte_chr.o byte_chr

byte_copy.o: \
default.o.build \
compile \
byte_copy.c \
byte.h
	sh makefile.build default.o.build byte_copy.o byte_copy

byte_cr.o: \
default.o.build \
compile \
byte_cr.c \
byte.h
	sh makefile.build default.o.build byte_cr.o byte_cr

byte_diff.o: \
default.o.build \
compile \
byte_diff.c \
byte.h
	sh makefile.build default.o.build byte_diff.o byte_diff

byte_zero.o: \
default.o.build \
compile \
byte_zero.c \
byte.h
	sh makefile.build default.o.build byte_zero.o byte_zero

ccperl: \
ccperl.build \
conf-ccperl \
conf-perl \
print-ccperl.sh
	sh makefile.build ccperl.build ccperl 

cdb.o: \
default.o.build \
compile \
cdb.c \
error.h \
seek.h \
byte.h \
uint32.h \
cdb.h
	sh makefile.build default.o.build cdb.o cdb

cdb_hash.o: \
default.o.build \
compile \
cdb_hash.c \
uint32.h \
cdb.h
	sh makefile.build default.o.build cdb_hash.o cdb_hash

cdb_make.o: \
default.o.build \
compile \
cdb_make.c \
seek.h \
error.h \
alloc.h \
cdb.h \
buffer.h \
uint32.h \
cdb_make.h
	sh makefile.build default.o.build cdb_make.o cdb_make

chkshsgr: \
default.build \
chkshsgr=x \
load \
chkshsgr.o
	sh makefile.build default.build chkshsgr chkshsgr

chkshsgr.o: \
default.o.build \
compile \
chkshsgr.c \
exit.h
	sh makefile.build default.o.build chkshsgr.o chkshsgr

choose: \
default.build \
choose=s \
makeinclude \
makescrip \
warn-auto.sh \
choose.sh
	sh makefile.build default.build choose choose

choosing: \
default.build \
choosing=s \
makeinclude \
makescrip \
warn-auto.sh \
choosing.sh
	sh makefile.build default.build choosing choosing

coe.o: \
default.o.build \
compile \
coe.c \
coe.h
	sh makefile.build default.o.build coe.o coe

compile: \
default.build \
conf-cc \
print-compile.sh \
systype \
warn-auto.sh
	sh makefile.build default.build compile compile

connect-io: \
default.build \
connect-io=x \
load \
connect-io.o \
unix.a
	sh makefile.build default.build connect-io connect-io

connect-io.o: \
default.o.build \
compile \
connect-io.c \
exit.h \
uint64.h \
tai.h \
taia.h \
iopause.h \
strerr.h \
scan.h \
ndelay.h \
sig.h
	sh makefile.build default.o.build connect-io.o connect-io

env.o: \
default.o.build \
compile \
env.c \
str.h \
env.h
	sh makefile.build default.o.build env.o env

error.o: \
default.o.build \
compile \
error.c \
error.h
	sh makefile.build default.o.build error.o error

error_str.o: \
default.o.build \
compile \
error_str.c \
error.h
	sh makefile.build default.o.build error_str.o error_str

fd_copy.o: \
default.o.build \
compile \
fd_copy.c \
fd.h
	sh makefile.build default.o.build fd_copy.o fd_copy

fd_move.o: \
default.o.build \
compile \
fd_move.c \
fd.h
	sh makefile.build default.o.build fd_move.o fd_move

fd_shutdown.o: \
default.o.build \
compile \
fd_shutdown.c \
fd.h \
error.h
	sh makefile.build default.o.build fd_shutdown.o fd_shutdown

fmt_ulong.o: \
default.o.build \
compile \
fmt_ulong.c \
fmt.h
	sh makefile.build default.o.build fmt_ulong.o fmt_ulong

fork.h: \
fork.h.build \
choose \
compile \
load \
tryvfork.c \
fork.h1 \
fork.h2
	sh makefile.build fork.h.build fork.h 

generic-conf.o: \
default.o.build \
compile \
generic-conf.c \
strerr.h \
open.h \
buffer.h \
generic-conf.h
	sh makefile.build default.o.build generic-conf.o generic-conf

getgid: \
default.build \
getgid=x \
load \
getgid.o \
unix.a
	sh makefile.build default.build getgid getgid

getgid.o: \
default.o.build \
compile \
getgid.c \
strerr.h \
fmt.h \
buffer.h \
exit.h
	sh makefile.build default.o.build getgid.o getgid

getln.o: \
default.o.build \
compile \
getln.c \
byte.h \
buffer.h \
gen_alloc.h \
stralloc.h \
getln.h
	sh makefile.build default.o.build getln.o getln

getln2.o: \
default.o.build \
compile \
getln2.c \
byte.h \
buffer.h \
gen_alloc.h \
stralloc.h \
getln.h
	sh makefile.build default.o.build getln2.o getln2

getpeereid.c: \
getpeereid.c.build \
systype \
compile \
load \
choosing \
trygpid.c \
trysopc.c \
getpeereid.so_peercred \
getpeereid.syscall \
getpeereid.oops
	sh makefile.build getpeereid.c.build getpeereid.c 

getpeereid.o: \
default.o.build \
compile \
getpeereid.c
	sh makefile.build default.o.build getpeereid.o getpeereid

getuid: \
default.build \
getuid=x \
load \
getuid.o \
unix.a
	sh makefile.build default.build getuid getuid

getuid.o: \
default.o.build \
compile \
getuid.c \
strerr.h \
fmt.h \
buffer.h \
exit.h
	sh makefile.build default.o.build getuid.o getuid

hasflock.h: \
hasflock.h.build \
choose \
compile \
load \
tryflock.c \
hasflock.h1 \
hasflock.h2
	sh makefile.build hasflock.h.build hasflock.h 

hassgact.h: \
hassgact.h.build \
choose \
compile \
trysgact.c \
hassgact.h1 \
hassgact.h2
	sh makefile.build hassgact.h.build hassgact.h 

hassgprm.h: \
hassgprm.h.build \
choose \
compile \
trysgprm.c \
hassgprm.h1 \
hassgprm.h2
	sh makefile.build hassgprm.h.build hassgprm.h 

hasshsgr.h: \
hasshsgr.h.build \
choose \
compile \
tryshsgr.c \
hasshsgr.h1 \
hasshsgr.h2 \
chkshsgr \
warn-shsgr
	sh makefile.build hasshsgr.h.build hasshsgr.h 

haswaitp.h: \
haswaitp.h.build \
choose \
compile \
load \
trywaitp.c \
haswaitp.h1 \
haswaitp.h2
	sh makefile.build haswaitp.h.build haswaitp.h 

home: \
home.build
	sh makefile.build home.build home 

iopause.h: \
iopause.h.build \
choose \
compile \
load \
trypoll.c \
iopause.h1 \
iopause.h2
	sh makefile.build iopause.h.build iopause.h 

iopause.o: \
default.o.build \
compile \
iopause.c \
select.h \
uint64.h \
tai.h \
taia.h \
iopause.h
	sh makefile.build default.o.build iopause.o iopause

iopause_proxy.o: \
default.o.build \
compile \
iopause_proxy.c \
uint64.h \
tai.h \
taia.h \
iopause.h \
buffer.h \
fd.h \
error.h
	sh makefile.build default.o.build iopause_proxy.o iopause_proxy

ipc_accept.o: \
default.o.build \
compile \
ipc_accept.c \
byte.h \
ipc.h
	sh makefile.build default.o.build ipc_accept.o ipc_accept

ipc_bind.o: \
default.o.build \
compile \
ipc_bind.c \
error.h \
byte.h \
str.h \
ipc.h \
ipcpath.h
	sh makefile.build default.o.build ipc_bind.o ipc_bind

ipc_conn.o: \
default.o.build \
compile \
ipc_conn.c \
error.h \
byte.h \
str.h \
ndelay.h \
ipc.h \
ipcpath.h
	sh makefile.build default.o.build ipc_conn.o ipc_conn

ipc_eid.o: \
default.o.build \
compile \
ipc_eid.c \
getpeereid.h \
ipc.h
	sh makefile.build default.o.build ipc_eid.o ipc_eid

ipc_listen.o: \
default.o.build \
compile \
ipc_listen.c \
ipc.h
	sh makefile.build default.o.build ipc_listen.o ipc_listen

ipc_local.o: \
default.o.build \
compile \
ipc_local.c \
byte.h \
ipc.h
	sh makefile.build default.o.build ipc_local.o ipc_local

ipc_stream.o: \
default.o.build \
compile \
ipc_stream.c \
ndelay.h \
ipc.h
	sh makefile.build default.o.build ipc_stream.o ipc_stream

ipcaccept: \
default.build \
ipcaccept=x \
load \
ipcaccept.o \
unix.a \
socket.lib
	sh makefile.build default.build ipcaccept ipcaccept

ipcaccept.o: \
default.o.build \
compile \
ipcaccept.c \
str.h \
byte.h \
fmt.h \
scan.h \
fd.h \
exit.h \
env.h \
prot.h \
open.h \
wait.h \
alloc.h \
buffer.h \
error.h \
strerr.h \
subgetopt.h \
sgetopt.h \
pathexec.h \
ipc.h \
ipcpath.h \
gen_alloc.h \
stralloc.h \
rules.h \
sig.h \
ndelay.h \
fork.h \
lock.h
	sh makefile.build default.o.build ipcaccept.o ipcaccept

ipccat: \
default.build \
ipccat=s \
makeinclude \
makescrip \
warn-auto.sh \
ipccat.sh
	sh makefile.build default.build ipccat ipccat

ipcclient: \
default.build \
ipcclient=x \
load \
ipcclient.o \
unix.a \
socket.lib
	sh makefile.build default.build ipcclient ipcclient

ipcclient.o: \
default.o.build \
compile \
ipcclient.c \
sig.h \
exit.h \
subgetopt.h \
sgetopt.h \
str.h \
ipc.h \
ipcpath.h \
fd.h \
buffer.h \
error.h \
strerr.h \
pathexec.h
	sh makefile.build default.o.build ipcclient.o ipcclient

ipccommand: \
default.build \
ipccommand=x \
load \
ipccommand.o \
unix.a
	sh makefile.build default.build ipccommand ipccommand

ipccommand.o: \
default.o.build \
compile \
ipccommand.c \
sig.h \
wait.h \
fork.h \
fmt.h \
scan.h \
buffer.h \
strerr.h \
str.h \
exit.h
	sh makefile.build default.o.build ipccommand.o ipccommand

ipcconnect: \
default.build \
ipcconnect=s \
makeinclude \
makescrip \
warn-auto.sh \
ipcconnect.sh
	sh makefile.build default.build ipcconnect ipcconnect

ipcdo: \
default.build \
ipcdo=s \
makeinclude \
makescrip \
warn-auto.sh \
ipcdo.sh
	sh makefile.build default.build ipcdo ipcdo

ipcexec: \
default.build \
ipcexec=x \
load \
ipcexec.o \
unix.a
	sh makefile.build default.build ipcexec ipcexec

ipcexec-config: \
default.build \
ipcexec-config=x \
load \
ipcexec-config.o \
unix.a \
auto_home.o
	sh makefile.build default.build ipcexec-config ipcexec-config

ipcexec-config.o: \
default.o.build \
compile \
ipcexec-config.c \
strerr.h \
exit.h \
auto_home.h \
buffer.h \
generic-conf.h \
fmt.h
	sh makefile.build default.o.build ipcexec-config.o ipcexec-config

ipcexec.o: \
default.o.build \
compile \
ipcexec.c \
str.h \
byte.h \
fmt.h \
scan.h \
exit.h \
prot.h \
open.h \
alloc.h \
buffer.h \
error.h \
strerr.h \
env.h \
pathexec.h \
gen_alloc.h \
stralloc.h \
rules.h \
fd.h
	sh makefile.build default.o.build ipcexec.o ipcexec

ipcexecrules: \
default.build \
ipcexecrules=x \
load \
ipcexecrules.o \
unix.a
	sh makefile.build default.build ipcexecrules ipcexecrules

ipcexecrules.o: \
default.o.build \
compile \
ipcexecrules.c \
strerr.h \
gen_alloc.h \
stralloc.h \
getln.h \
exit.h \
fmt.h \
scan.h \
byte.h \
buffer.h \
uint32.h \
cdb_make.h \
open.h
	sh makefile.build default.o.build ipcexecrules.o ipcexecrules

ipcexecrulescheck: \
default.build \
ipcexecrulescheck=x \
load \
ipcexecrulescheck.o \
unix.a
	sh makefile.build default.build ipcexecrulescheck ipcexecrulescheck

ipcexecrulescheck.o: \
default.o.build \
compile \
ipcexecrulescheck.c \
byte.h \
buffer.h \
strerr.h \
env.h \
rules.h \
gen_alloc.h \
stralloc.h \
open.h \
exit.h
	sh makefile.build default.o.build ipcexecrulescheck.o ipcexecrulescheck

ipchandle.o: \
default.o.build \
compile \
ipchandle.c \
uint16.h \
str.h \
byte.h \
fmt.h \
scan.h \
ip4.h \
fd.h \
exit.h \
env.h \
prot.h \
open.h \
wait.h \
alloc.h \
buffer.h \
error.h \
strerr.h \
subgetopt.h \
sgetopt.h \
ipc.h \
ipcpath.h \
ndelay.h \
gen_alloc.h \
stralloc.h \
rules.h \
sig.h \
uint64.h \
tai.h \
taia.h \
iopause.h \
coe.h \
lock.h
	sh makefile.build default.o.build ipchandle.o ipchandle

ipclisten: \
default.build \
ipclisten=x \
load \
ipclisten.o \
unix.a \
socket.lib
	sh makefile.build default.build ipclisten ipclisten

ipclisten.o: \
default.o.build \
compile \
ipclisten.c \
str.h \
byte.h \
fmt.h \
scan.h \
fd.h \
exit.h \
env.h \
prot.h \
open.h \
wait.h \
gen_alloc.h \
stralloc.h \
alloc.h \
buffer.h \
error.h \
strerr.h \
subgetopt.h \
sgetopt.h \
pathexec.h \
ipc.h \
ipcpath.h \
sig.h \
ndelay.h \
fork.h
	sh makefile.build default.o.build ipclisten.o ipclisten

ipcpath.h: \
ipcpath.h.build \
compile \
tryipcpath \
print-ipcpath.sh
	sh makefile.build ipcpath.h.build ipcpath.h 

ipcperl: \
default.build \
ipcperl=x \
load \
ipcperl.o \
ipchandle.o \
unix.a \
socket.lib \
perlembed.lib
	sh makefile.build default.build ipcperl ipcperl

ipcperl.command: \
default.command.build \
ipcperl \
ipcperl=d
	sh makefile.build default.command.build ipcperl.command ipcperl

ipcperl.o: \
ipcperl.o.build \
compile \
ccperl \
ipcperl.c \
strerr.h \
gen_alloc.h \
stralloc.h \
str.h
	sh makefile.build ipcperl.o.build ipcperl.o 

ipcperl.rts: \
default.rts.build \
ipcperl.command
	sh makefile.build default.rts.build ipcperl.rts ipcperl

ipcprint: \
default.build \
ipcprint=x \
load \
ipcprint.o \
ipchandle.o \
unix.a \
socket.lib
	sh makefile.build default.build ipcprint ipcprint

ipcprint.o: \
default.o.build \
compile \
ipcprint.c \
buffer.h \
env.h
	sh makefile.build default.o.build ipcprint.o ipcprint

ipcrules: \
default.build \
ipcrules=x \
load \
ipcrules.o \
unix.a
	sh makefile.build default.build ipcrules ipcrules

ipcrules.o: \
default.o.build \
compile \
ipcrules.c \
strerr.h \
gen_alloc.h \
stralloc.h \
getln.h \
exit.h \
fmt.h \
byte.h \
buffer.h \
uint32.h \
cdb_make.h \
scan.h \
open.h
	sh makefile.build default.o.build ipcrules.o ipcrules

ipcrulescheck: \
default.build \
ipcrulescheck=x \
load \
ipcrulescheck.o \
unix.a
	sh makefile.build default.build ipcrulescheck ipcrulescheck

ipcrulescheck.o: \
default.o.build \
compile \
ipcrulescheck.c \
byte.h \
buffer.h \
strerr.h \
env.h \
open.h \
gen_alloc.h \
stralloc.h \
rules.h \
exit.h
	sh makefile.build default.o.build ipcrulescheck.o ipcrulescheck

ipcrun: \
default.build \
ipcrun=s \
makeinclude \
makescrip \
warn-auto.sh \
ipcrun.sh
	sh makefile.build default.build ipcrun ipcrun

ipcserver: \
default.build \
ipcserver=x \
load \
ipcserver.o \
unix.a \
socket.lib
	sh makefile.build default.build ipcserver ipcserver

ipcserver.o: \
default.o.build \
compile \
ipcserver.c \
str.h \
byte.h \
fmt.h \
scan.h \
fd.h \
exit.h \
env.h \
prot.h \
open.h \
wait.h \
alloc.h \
buffer.h \
error.h \
strerr.h \
subgetopt.h \
sgetopt.h \
pathexec.h \
ipc.h \
ipcpath.h \
gen_alloc.h \
stralloc.h \
rules.h \
sig.h \
ndelay.h \
fork.h
	sh makefile.build default.o.build ipcserver.o ipcserver

it: \
default.build \
it=d \
ipcclient \
ipcserver \
ipccat \
ipcconnect \
ipcrules \
ipcrulescheck \
ipcexecrules \
ipcexecrulescheck \
ipcdo \
ipccommand \
ipcexec \
ipcrun \
ipcexec-config \
ipcprint \
getuid \
getgid \
connect-io \
ipclisten \
ipcaccept
	sh makefile.build default.build it it

it.command: \
default.command.build \
it \
it=d
	sh makefile.build default.command.build it.command it

it.rts: \
default.rts.build \
it.command
	sh makefile.build default.rts.build it.rts it

load: \
default.build \
conf-ld \
print-load.sh \
warn-auto.sh
	sh makefile.build default.build load load

lock_ex.o: \
default.o.build \
compile \
lock_ex.c \
hasflock.h \
lock.h
	sh makefile.build default.o.build lock_ex.o lock_ex

lock_un.o: \
default.o.build \
compile \
lock_un.c \
hasflock.h \
lock.h
	sh makefile.build default.o.build lock_un.o lock_un

makeinclude: \
default.build \
makeinclude.sh \
warn-auto.sh
	sh makefile.build default.build makeinclude makeinclude

makelib: \
default.build \
print-ar.sh \
systype \
warn-auto.sh
	sh makefile.build default.build makelib makelib

makescrip: \
default.build \
warn-auto.sh \
print-makescrip.sh \
conf-scrip \
home \
conf-ipcexec
	sh makefile.build default.build makescrip makescrip

mkfile: \
mkfile.build \
mkfile=d \
it.command \
it.rts \
ipcperl.command \
ipcperl.rts
	sh makefile.build mkfile.build mkfile 

ndelay_off.o: \
default.o.build \
compile \
ndelay_off.c \
ndelay.h
	sh makefile.build default.o.build ndelay_off.o ndelay_off

ndelay_on.o: \
default.o.build \
compile \
ndelay_on.c \
ndelay.h
	sh makefile.build default.o.build ndelay_on.o ndelay_on

open_append.o: \
default.o.build \
compile \
open_append.c \
open.h
	sh makefile.build default.o.build open_append.o open_append

open_read.o: \
default.o.build \
compile \
open_read.c \
open.h
	sh makefile.build default.o.build open_read.o open_read

open_trunc.o: \
default.o.build \
compile \
open_trunc.c \
open.h
	sh makefile.build default.o.build open_trunc.o open_trunc

pathexec_env.o: \
default.o.build \
compile \
pathexec_env.c \
gen_alloc.h \
stralloc.h \
alloc.h \
str.h \
byte.h \
env.h \
pathexec.h
	sh makefile.build default.o.build pathexec_env.o pathexec_env

pathexec_run.o: \
default.o.build \
compile \
pathexec_run.c \
error.h \
gen_alloc.h \
stralloc.h \
str.h \
env.h \
pathexec.h
	sh makefile.build default.o.build pathexec_run.o pathexec_run

perlembed.lib: \
perlembed.lib.build \
conf-perl \
conf-ldperl \
print-perlembed.sh
	sh makefile.build perlembed.lib.build perlembed.lib 

prot.o: \
default.o.build \
compile \
prot.c \
hasshsgr.h \
prot.h
	sh makefile.build default.o.build prot.o prot

rules.o: \
default.o.build \
compile \
rules.c \
alloc.h \
open.h \
uint32.h \
cdb.h \
gen_alloc.h \
stralloc.h \
rules.h
	sh makefile.build default.o.build rules.o rules

scan_uint.o: \
default.o.build \
compile \
scan_uint.c \
scan.h
	sh makefile.build default.o.build scan_uint.o scan_uint

scan_ulong.o: \
default.o.build \
compile \
scan_ulong.c \
scan.h
	sh makefile.build default.o.build scan_ulong.o scan_ulong

seek_set.o: \
default.o.build \
compile \
seek_set.c \
seek.h
	sh makefile.build default.o.build seek_set.o seek_set

select.h: \
select.h.build \
choose \
compile \
trysysel.c \
select.h1 \
select.h2
	sh makefile.build select.h.build select.h 

sgetopt.o: \
default.o.build \
compile \
sgetopt.c \
buffer.h \
sgetopt.h \
subgetopt.h
	sh makefile.build default.o.build sgetopt.o sgetopt

sig.o: \
default.o.build \
compile \
sig.c \
sig.h
	sh makefile.build default.o.build sig.o sig

sig_block.o: \
default.o.build \
compile \
sig_block.c \
sig.h \
hassgprm.h
	sh makefile.build default.o.build sig_block.o sig_block

sig_catch.o: \
default.o.build \
compile \
sig_catch.c \
sig.h \
hassgact.h
	sh makefile.build default.o.build sig_catch.o sig_catch

sig_pause.o: \
default.o.build \
compile \
sig_pause.c \
sig.h \
hassgprm.h
	sh makefile.build default.o.build sig_pause.o sig_pause

socket.lib: \
default.lib.build \
trylsock.c \
compile \
load
	sh makefile.build default.lib.build socket.lib socket

str_chr.o: \
default.o.build \
compile \
str_chr.c \
str.h
	sh makefile.build default.o.build str_chr.o str_chr

str_diff.o: \
default.o.build \
compile \
str_diff.c \
str.h
	sh makefile.build default.o.build str_diff.o str_diff

str_len.o: \
default.o.build \
compile \
str_len.c \
str.h
	sh makefile.build default.o.build str_len.o str_len

str_start.o: \
default.o.build \
compile \
str_start.c \
str.h
	sh makefile.build default.o.build str_start.o str_start

stralloc_cat.o: \
default.o.build \
compile \
stralloc_cat.c \
byte.h \
gen_alloc.h \
stralloc.h
	sh makefile.build default.o.build stralloc_cat.o stralloc_cat

stralloc_catb.o: \
default.o.build \
compile \
stralloc_catb.c \
gen_alloc.h \
stralloc.h \
byte.h
	sh makefile.build default.o.build stralloc_catb.o stralloc_catb

stralloc_cats.o: \
default.o.build \
compile \
stralloc_cats.c \
byte.h \
str.h \
gen_alloc.h \
stralloc.h
	sh makefile.build default.o.build stralloc_cats.o stralloc_cats

stralloc_copy.o: \
default.o.build \
compile \
stralloc_copy.c \
byte.h \
gen_alloc.h \
stralloc.h
	sh makefile.build default.o.build stralloc_copy.o stralloc_copy

stralloc_eady.o: \
default.o.build \
compile \
stralloc_eady.c \
alloc.h \
gen_alloc.h \
stralloc.h \
gen_allocdefs.h
	sh makefile.build default.o.build stralloc_eady.o stralloc_eady

stralloc_opyb.o: \
default.o.build \
compile \
stralloc_opyb.c \
gen_alloc.h \
stralloc.h \
byte.h
	sh makefile.build default.o.build stralloc_opyb.o stralloc_opyb

stralloc_opys.o: \
default.o.build \
compile \
stralloc_opys.c \
byte.h \
str.h \
gen_alloc.h \
stralloc.h
	sh makefile.build default.o.build stralloc_opys.o stralloc_opys

stralloc_pend.o: \
default.o.build \
compile \
stralloc_pend.c \
alloc.h \
gen_alloc.h \
stralloc.h \
gen_allocdefs.h
	sh makefile.build default.o.build stralloc_pend.o stralloc_pend

strerr_die.o: \
default.o.build \
compile \
strerr_die.c \
buffer.h \
exit.h \
strerr.h
	sh makefile.build default.o.build strerr_die.o strerr_die

strerr_sys.o: \
default.o.build \
compile \
strerr_sys.c \
error.h \
strerr.h
	sh makefile.build default.o.build strerr_sys.o strerr_sys

subgetopt.o: \
default.o.build \
compile \
subgetopt.c \
subgetopt.h
	sh makefile.build default.o.build subgetopt.o subgetopt

systype: \
default.build \
find-systype.sh \
trycpp.c \
x86cpuid.c
	sh makefile.build default.build systype systype

tai_pack.o: \
default.o.build \
compile \
tai_pack.c \
uint64.h \
tai.h
	sh makefile.build default.o.build tai_pack.o tai_pack

taia_add.o: \
default.o.build \
compile \
taia_add.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_add.o taia_add

taia_approx.o: \
default.o.build \
compile \
taia_approx.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_approx.o taia_approx

taia_frac.o: \
default.o.build \
compile \
taia_frac.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_frac.o taia_frac

taia_less.o: \
default.o.build \
compile \
taia_less.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_less.o taia_less

taia_now.o: \
default.o.build \
compile \
taia_now.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_now.o taia_now

taia_pack.o: \
default.o.build \
compile \
taia_pack.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_pack.o taia_pack

taia_sub.o: \
default.o.build \
compile \
taia_sub.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_sub.o taia_sub

taia_uint.o: \
default.o.build \
compile \
taia_uint.c \
uint64.h \
tai.h \
taia.h
	sh makefile.build default.o.build taia_uint.o taia_uint

tryipcpath: \
default.build \
tryipcpath=x \
load \
tryipcpath.o \
fmt_ulong.o
	sh makefile.build default.build tryipcpath tryipcpath

tryipcpath.o: \
default.o.build \
compile \
tryipcpath.c \
fmt.h
	sh makefile.build default.o.build tryipcpath.o tryipcpath

uint32.h: \
uint32.h.build \
choose \
compile \
load \
tryulong32.c \
uint32.h1 \
uint32.h2
	sh makefile.build uint32.h.build uint32.h 

uint32_pack.o: \
default.o.build \
compile \
uint32_pack.c \
uint32.h
	sh makefile.build default.o.build uint32_pack.o uint32_pack

uint32_unpack.o: \
default.o.build \
compile \
uint32_unpack.c \
uint32.h
	sh makefile.build default.o.build uint32_unpack.o uint32_unpack

uint64.h: \
uint64.h.build \
choose \
compile \
load \
tryulong64.c \
uint64.h1 \
uint64.h2
	sh makefile.build uint64.h.build uint64.h 

unix.a: \
default.a.build \
unix=l \
makelib \
alloc.o \
alloc_re.o \
buffer.o \
buffer_0.o \
buffer_1.o \
buffer_2.o \
buffer_get.o \
buffer_put.o \
buffer_copy.o \
buffer_read.o \
buffer_write.o \
env.o \
error.o \
error_str.o \
fd_copy.o \
fd_move.o \
fd_shutdown.o \
fmt_ulong.o \
scan_ulong.o \
scan_uint.o \
getln.o \
getln2.o \
ipc_accept.o \
ipc_bind.o \
ipc_conn.o \
ipc_listen.o \
ipc_local.o \
ipc_eid.o \
ipc_stream.o \
ndelay_on.o \
ndelay_off.o \
open_read.o \
open_trunc.o \
open_append.o \
pathexec_env.o \
pathexec_run.o \
prot.o \
seek_set.o \
sgetopt.o \
sig.o \
sig_block.o \
sig_catch.o \
sig_pause.o \
str_chr.o \
str_diff.o \
str_len.o \
str_start.o \
stralloc_cat.o \
stralloc_catb.o \
stralloc_cats.o \
stralloc_copy.o \
stralloc_eady.o \
stralloc_opyb.o \
stralloc_opys.o \
stralloc_pend.o \
strerr_die.o \
strerr_sys.o \
subgetopt.o \
wait_nohang.o \
wait_pid.o \
iopause.o \
iopause_proxy.o \
tai_pack.o \
taia_add.o \
taia_approx.o \
taia_frac.o \
taia_less.o \
taia_now.o \
taia_pack.o \
taia_sub.o \
taia_uint.o \
getpeereid.o \
cdb.o \
cdb_hash.o \
cdb_make.o \
byte_zero.o \
byte_copy.o \
byte_chr.o \
byte_diff.o \
byte_cr.o \
rules.o \
uint32_pack.o \
uint32_unpack.o \
generic-conf.o \
lock_ex.o \
lock_un.o \
coe.o
	sh makefile.build default.a.build unix.a unix

wait_nohang.o: \
default.o.build \
compile \
wait_nohang.c \
haswaitp.h
	sh makefile.build default.o.build wait_nohang.o wait_nohang

wait_pid.o: \
default.o.build \
compile \
wait_pid.c \
error.h \
haswaitp.h
	sh makefile.build default.o.build wait_pid.o wait_pid
