#!/bin/sh
shout() { echo "package/build-run: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }
safe() { "$@" || barf "cannot $@"; }
usage() {
  shout "usage: package/build-run [ --help -v N -f -F ] compile src mode target ..."
  exit 100
}
####
verbose="1"
force="0"
while [ $# -gt 0 ]
do
  case "$1" in
    -F)
      force="2"
      shift
      ;;
    -f)
      force="1"
      shift
      ;;
    -v)
      shift
      verbose="$1"
      shift
      ;;
    -*)
      usage
      ;;
    *)
      break
      ;;
  esac
done
[ "$1" = "--help" ] && usage
#####
# NB: May have no targets.
[ $# -ge 3 ] || usage
compile="$1"
src="$2"
mode="$3"
shift; shift; shift
####
umask 022
[ -d package ] || barf "no package directory"
[ -d "$src"     ] || barf "no $src directory"
####
db_file=".build"
here=`env - PATH=$PATH pwd`
# FIXME: Still needed?
PATH="$here/$compile:/command:$PATH"
export PATH
#
safe mkdir -p "$compile"
[ -d "$compile" ] || barf "no $compile directory"
#
# Must precede build-linksrc call.
if [ $force -eq 2 ]
then
  rm -r "$compile"
  safe mkdir -p "$compile"
fi

safe cd "$compile"
if [ $force -eq 1 ]
then
  for target in ${1+"$@"}
  do
    "$here/package/build-uptodate" -v "$verbose" -b "$db_file" remove "$target"
    [ $? -eq 0 ] || barf "cannot $here/package/build-uptodate -v $verbose -b $db_file remove $target"
    safe rm -f -- "$target"
  done
fi

safe cd "$here"
safe package/build-linksrc "$compile" "$src"
safe cd "$compile"

# FIXME: Put list into config file?
sigprog=""
if which md5 >/dev/null
then
  sigprog="md5 -q"
else if which md5sum >/dev/null
then
  sigprog="md5sum"
else
  sigprog="cksum"
fi fi

if [ -r .build.sig ]
then
  buildsig="`head -1 ./.build.sig`"
  if [ "$buildsig" != "$sigprog" ]
  then
    echo "$sigprog" > .build.sig
  fi
else
  echo "$sigprog" > .build.sig
fi

# FIXME: options for make.
case "$mode" in
  compile)
    safe make ${1+"$@"}
    ;;
  build)
    safe "$here/package/build-targ" -b "$db_file" -v "$verbose" ${1+"$@"}
    ;;
  *)
    barf "unrecognized mode: $mode"
    ;;
esac

exit 0
