#!/bin/sh
shout() { echo "package/build: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }
safe() { "$@" || barf "cannot $@"; }
usage() {
  shout "usage: package/build [ --help -v N -f -F -p -P ] [ target ... ]"
  exit 100
}
####
umask 022
[ -d package ] || barf "no package directory"
[ -d src     ] || barf "no src directory"
here=`env - PATH=$PATH pwd`
#PATH="$here/compile:/command:$PATH"
#export PATH
#
[ "$1" = "--help" ] && usage
#
verbose="1"
force=""
parts=""
while [ $# -gt 0 ]
do
  case "$1" in
    -v)
      shift
      verbose="$1"
      shift
      ;;
    -f)
      force="-f"
      shift
      ;;
    -F)
      force="-F"
      shift
      ;;
    -p)
      parts="true"
      shift
      ;;
    -P)
      parts=""
      shift
      ;;
    -*)
      usage
      ;;
    *)
      break
      ;;
  esac
done
#
if [ $# -gt 0 ]
then
  if [ "true" = "$parts" ]
  then
    commands="`package/parts target "$@" < package/commands`"
    safe package/build-run $force compile src build $commands
    safe package/build-command command compile $commands
  else
    safe package/build-run $force compile src build "$@"
    safe package/build-command command compile "$@"
  fi
else
  safe package/build-run $force compile src build it
  safe package/build-command command compile `awk '{ print $1 }' < package/commands`
fi
exit 0
